server:
  port: '8080'

bot:
  name: Chords Topic Bot
  webhook-path: https://cacb-194-226-248-0.eu.ngrok.io
  topic-page-capability: '15'
  token: this is secret :)

cache-cleaner:
  config: 30 0 2 * * *

parser:
  port: '8050'
  request:
    sort: position
    size: 10

