bot:
  name: Chords Topic Bot
  webhook-path: https://cacb-194-226-248-0.eu.ngrok.io
  topic-page-capability: '15'
  token: 5605033533:AAHEd_vnu9mleplw4VXKNBXozHZ-ABZmWdk

server:
  port: '80'

cache-cleaner:
  config: 30 0 2 * * *

parser:
  port: '50'
  request:
    sort: position
    size: 10

